# Generated by Django 5.0.6 on 2024-07-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_book_author_book_shop_book_author_8c18bb_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip_code_code',
            new_name='zip_code',
        ),
    ]
